/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    media: Media;
    file: File;
    'hero-banner': HeroBanner;
    broadcast: Broadcast;
    achievement: Achievement;
    'kd-department': KdDepartment;
    'staff-directory': StaffDirectory;
    policy: Policy;
    'quick-link': QuickLink;
    celebration: Celebration;
    feedback: Feedback;
    search: Search;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    file: FileSelect<false> | FileSelect<true>;
    'hero-banner': HeroBannerSelect<false> | HeroBannerSelect<true>;
    broadcast: BroadcastSelect<false> | BroadcastSelect<true>;
    achievement: AchievementSelect<false> | AchievementSelect<true>;
    'kd-department': KdDepartmentSelect<false> | KdDepartmentSelect<true>;
    'staff-directory': StaffDirectorySelect<false> | StaffDirectorySelect<true>;
    policy: PolicySelect<false> | PolicySelect<true>;
    'quick-link': QuickLinkSelect<false> | QuickLinkSelect<true>;
    celebration: CelebrationSelect<false> | CelebrationSelect<true>;
    feedback: FeedbackSelect<false> | FeedbackSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    'feedback-settings': FeedbackSetting;
    'site-info': SiteInfo;
    header: Header;
    footer: Footer;
    homepage: Homepage;
    'profil-kementerian': ProfilKementerian;
  };
  globalsSelect: {
    'feedback-settings': FeedbackSettingsSelect<false> | FeedbackSettingsSelect<true>;
    'site-info': SiteInfoSelect<false> | SiteInfoSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'profil-kementerian': ProfilKementerianSelect<false> | ProfilKementerianSelect<true>;
  };
  locale: 'ms-MY' | 'en-GB';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role?: ('admin' | 'user') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "file".
 */
export interface File {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename: string;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This is the file upload collection meant for Celebration collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-banner".
 */
export interface HeroBanner {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename: string;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "broadcast".
 */
export interface Broadcast {
  id: string;
  title: string;
  /**
   * Use as the URL link for broadcast page
   */
  slug: string;
  type: 'announcement' | 'media_release' | 'speech';
  date: string;
  description: string;
  broadcast_text: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  broadcast_text_html?: string | null;
  isPin?: boolean | null;
  broadcast_image?: (string | null) | Media;
  broadcast_file_eng?: (string | null) | File;
  broadcast_file_bm?: (string | null) | File;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievement".
 */
export interface Achievement {
  id: string;
  title: string;
  type: 'product_launch' | 'policy' | 'collaboration' | 'miscellaneous' | 'not_achievement';
  date: string;
  description: string;
  content_text?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  isFlagged?: boolean | null;
  achievement_file?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kd-department".
 */
export interface KdDepartment {
  id: string;
  id_bhg: number;
  bhg: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff-directory".
 */
export interface StaffDirectory {
  id: string;
  id_bhg: string | KdDepartment;
  /**
   * Use 0 for vacant position and -1 for department section
   */
  staff_id: number;
  nama?: string | null;
  gred?: string | null;
  jawatan?: string | null;
  telefon?: string | null;
  laman?: string | null;
  emel?: string | null;
  image?: (string | null) | Media;
  social_media?:
    | {
        social: 'Facebook' | 'X' | 'Instagram' | 'Tiktok';
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | (
                | '/'
                | '/pencapaian'
                | '/siaran'
                | '/hubungi-kami'
                | '/profil-kementerian'
                | '/direktori'
                | '/penafian'
                | '/dasar'
                | '/dasar-privasi'
              )
            | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy".
 */
export interface Policy {
  id: string;
  doc_name: string;
  doc_type: 'act' | 'document' | 'guideline' | 'circular';
  doc_description: string;
  doc_date: string;
  file_upload: string | File;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quick-link".
 */
export interface QuickLink {
  id: string;
  name: string;
  type?: ('social' | 'quick_links') | null;
  description?: string | null;
  href: {
    link?: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | (
            | '/'
            | '/pencapaian'
            | '/siaran'
            | '/hubungi-kami'
            | '/profil-kementerian'
            | '/direktori'
            | '/penafian'
            | '/dasar'
            | '/dasar-privasi'
          )
        | null;
      url?: string | null;
    };
    id?: string | null;
  }[];
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hero Banner for celebration. This collection meant for celebration in Malaysia designed for use in hero banner in home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "celebration".
 */
export interface Celebration {
  id: string;
  title: string;
  /**
   * Add the top gradient color. Use #FFFFFF
   */
  'top-gradient': string;
  /**
   * Add the middle gradient color. Use #FFFFFF
   */
  'middle-gradient': string;
  /**
   * Add the bottom gradient color. Use #FFFFFF
   */
  'bottom-gradient': string;
  /**
   * This is the desktop design. Fill in the fields accordingly for desktop design
   */
  desktop: {
    file_desktop: string | HeroBanner;
    type: 'desktop' | 'mobile';
  };
  /**
   * This is the mobile design. Fill in the fields accordingly for mobile design
   */
  mobile: {
    file_mobile: string | HeroBanner;
    type: 'desktop' | 'mobile';
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback".
 */
export interface Feedback {
  id: string;
  type: 'aduan' | 'pertanyaan' | 'cadangan';
  name: string;
  ic_number: string;
  address: string;
  phone_country_code: string;
  phone: string;
  email: string;
  agency: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'achievement';
        value: string | Achievement;
      }
    | {
        relationTo: 'broadcast';
        value: string | Broadcast;
      }
    | {
        relationTo: 'staff-directory';
        value: string | StaffDirectory;
      }
    | {
        relationTo: 'policy';
        value: string | Policy;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'file';
        value: string | File;
      } | null)
    | ({
        relationTo: 'hero-banner';
        value: string | HeroBanner;
      } | null)
    | ({
        relationTo: 'broadcast';
        value: string | Broadcast;
      } | null)
    | ({
        relationTo: 'achievement';
        value: string | Achievement;
      } | null)
    | ({
        relationTo: 'kd-department';
        value: string | KdDepartment;
      } | null)
    | ({
        relationTo: 'staff-directory';
        value: string | StaffDirectory;
      } | null)
    | ({
        relationTo: 'policy';
        value: string | Policy;
      } | null)
    | ({
        relationTo: 'quick-link';
        value: string | QuickLink;
      } | null)
    | ({
        relationTo: 'celebration';
        value: string | Celebration;
      } | null)
    | ({
        relationTo: 'feedback';
        value: string | Feedback;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "file_select".
 */
export interface FileSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-banner_select".
 */
export interface HeroBannerSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "broadcast_select".
 */
export interface BroadcastSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  date?: T;
  description?: T;
  broadcast_text?: T;
  broadcast_text_html?: T;
  isPin?: T;
  broadcast_image?: T;
  broadcast_file_eng?: T;
  broadcast_file_bm?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievement_select".
 */
export interface AchievementSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  date?: T;
  description?: T;
  content_text?: T;
  isFlagged?: T;
  achievement_file?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kd-department_select".
 */
export interface KdDepartmentSelect<T extends boolean = true> {
  id_bhg?: T;
  bhg?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff-directory_select".
 */
export interface StaffDirectorySelect<T extends boolean = true> {
  id_bhg?: T;
  staff_id?: T;
  nama?: T;
  gred?: T;
  jawatan?: T;
  telefon?: T;
  laman?: T;
  emel?: T;
  image?: T;
  social_media?:
    | T
    | {
        social?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy_select".
 */
export interface PolicySelect<T extends boolean = true> {
  doc_name?: T;
  doc_type?: T;
  doc_description?: T;
  doc_date?: T;
  file_upload?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quick-link_select".
 */
export interface QuickLinkSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  description?: T;
  href?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
            };
        id?: T;
      };
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "celebration_select".
 */
export interface CelebrationSelect<T extends boolean = true> {
  title?: T;
  'top-gradient'?: T;
  'middle-gradient'?: T;
  'bottom-gradient'?: T;
  desktop?:
    | T
    | {
        file_desktop?: T;
        type?: T;
      };
  mobile?:
    | T
    | {
        file_mobile?: T;
        type?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback_select".
 */
export interface FeedbackSelect<T extends boolean = true> {
  type?: T;
  name?: T;
  ic_number?: T;
  address?: T;
  phone_country_code?: T;
  phone?: T;
  email?: T;
  agency?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback-settings".
 */
export interface FeedbackSetting {
  id: string;
  adminEmail: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-info".
 */
export interface SiteInfo {
  id: string;
  site_name: string;
  address: string;
  /**
   * Add the address to use for using with Google Maps or Waze, ie, Menara Usahawan
   */
  map_address: string;
  encoded_address?: string | null;
  no_tel: string;
  email: string;
  social_media: {
    social: 'Facebook' | 'X' | 'Instagram' | 'Tiktok';
    link: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | (
            | '/'
            | '/pencapaian'
            | '/siaran'
            | '/hubungi-kami'
            | '/profil-kementerian'
            | '/direktori'
            | '/penafian'
            | '/dasar'
            | '/dasar-privasi'
          )
        | null;
      url?: string | null;
      label: string;
    };
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  items: {
    link: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | (
            | '/'
            | '/pencapaian'
            | '/siaran'
            | '/hubungi-kami'
            | '/profil-kementerian'
            | '/direktori'
            | '/penafian'
            | '/dasar'
            | '/dasar-privasi'
          )
        | null;
      url?: string | null;
      label: string;
    };
    id?: string | null;
  }[];
  dropdown: {
    name: string;
    dept_agency?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | (
                  | '/'
                  | '/pencapaian'
                  | '/siaran'
                  | '/hubungi-kami'
                  | '/profil-kementerian'
                  | '/direktori'
                  | '/penafian'
                  | '/dasar'
                  | '/dasar-privasi'
                )
              | null;
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  about_us?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | (
                | '/'
                | '/pencapaian'
                | '/siaran'
                | '/hubungi-kami'
                | '/profil-kementerian'
                | '/direktori'
                | '/penafian'
                | '/dasar'
                | '/dasar-privasi'
              )
            | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  'quick-links'?:
    | {
        'quick-links'?: (string | null) | QuickLink;
        id?: string | null;
      }[]
    | null;
  'open-source'?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | (
                | '/'
                | '/pencapaian'
                | '/siaran'
                | '/hubungi-kami'
                | '/profil-kementerian'
                | '/direktori'
                | '/penafian'
                | '/dasar'
                | '/dasar-privasi'
              )
            | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  disclaimer_section?: {
    statement?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  'privacy-policy_section'?: {
    statement?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: string;
  hero_banner?: (string | null) | Celebration;
  featured_achievements: {
    achievements: string | Achievement;
    id?: string | null;
  }[];
  quick_links: {
    links: string | QuickLink;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profil-kementerian".
 */
export interface ProfilKementerian {
  id: string;
  vision: {
    statement: string;
    icon:
      | 'arrow-back'
      | 'arrow-down'
      | 'arrow-forward'
      | 'arrow-outgoing'
      | 'arrow-up'
      | 'bolt'
      | 'check-circle'
      | 'checkmark-14-point-star'
      | 'checkmark-shield'
      | 'chevron-down'
      | 'chevron-left'
      | 'chevron-right'
      | 'chevron-up'
      | 'cross-x'
      | 'direction'
      | 'ellipsis'
      | 'envelope'
      | 'eye-show'
      | 'file-document-paper'
      | 'flag'
      | 'globe'
      | 'gov'
      | 'hamburger-menu'
      | 'lock'
      | 'map'
      | 'minus'
      | 'money'
      | 'phone'
      | 'search'
      | 'solid-lock'
      | 'star'
      | 'trophy'
      | 'user-group';
  };
  mission: {
    statement: string;
    icon:
      | 'arrow-back'
      | 'arrow-down'
      | 'arrow-forward'
      | 'arrow-outgoing'
      | 'arrow-up'
      | 'bolt'
      | 'check-circle'
      | 'checkmark-14-point-star'
      | 'checkmark-shield'
      | 'chevron-down'
      | 'chevron-left'
      | 'chevron-right'
      | 'chevron-up'
      | 'cross-x'
      | 'direction'
      | 'ellipsis'
      | 'envelope'
      | 'eye-show'
      | 'file-document-paper'
      | 'flag'
      | 'globe'
      | 'gov'
      | 'hamburger-menu'
      | 'lock'
      | 'map'
      | 'minus'
      | 'money'
      | 'phone'
      | 'search'
      | 'solid-lock'
      | 'star'
      | 'trophy'
      | 'user-group';
  };
  functions_and_role: {
    statement: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    icon:
      | 'arrow-back'
      | 'arrow-down'
      | 'arrow-forward'
      | 'arrow-outgoing'
      | 'arrow-up'
      | 'bolt'
      | 'check-circle'
      | 'checkmark-14-point-star'
      | 'checkmark-shield'
      | 'chevron-down'
      | 'chevron-left'
      | 'chevron-right'
      | 'chevron-up'
      | 'cross-x'
      | 'direction'
      | 'ellipsis'
      | 'envelope'
      | 'eye-show'
      | 'file-document-paper'
      | 'flag'
      | 'globe'
      | 'gov'
      | 'hamburger-menu'
      | 'lock'
      | 'map'
      | 'minus'
      | 'money'
      | 'phone'
      | 'search'
      | 'solid-lock'
      | 'star'
      | 'trophy'
      | 'user-group';
    id?: string | null;
  }[];
  leaders?:
    | {
        staff: string | StaffDirectory;
        id?: string | null;
      }[]
    | null;
  'latar-belakang'?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback-settings_select".
 */
export interface FeedbackSettingsSelect<T extends boolean = true> {
  adminEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-info_select".
 */
export interface SiteInfoSelect<T extends boolean = true> {
  site_name?: T;
  address?: T;
  map_address?: T;
  encoded_address?: T;
  no_tel?: T;
  email?: T;
  social_media?:
    | T
    | {
        social?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  items?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  dropdown?:
    | T
    | {
        name?: T;
        dept_agency?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  about_us?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  'quick-links'?:
    | T
    | {
        'quick-links'?: T;
        id?: T;
      };
  'open-source'?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  disclaimer_section?:
    | T
    | {
        statement?: T;
      };
  'privacy-policy_section'?:
    | T
    | {
        statement?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero_banner?: T;
  featured_achievements?:
    | T
    | {
        achievements?: T;
        id?: T;
      };
  quick_links?:
    | T
    | {
        links?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profil-kementerian_select".
 */
export interface ProfilKementerianSelect<T extends boolean = true> {
  vision?:
    | T
    | {
        statement?: T;
        icon?: T;
      };
  mission?:
    | T
    | {
        statement?: T;
        icon?: T;
      };
  functions_and_role?:
    | T
    | {
        statement?: T;
        icon?: T;
        id?: T;
      };
  leaders?:
    | T
    | {
        staff?: T;
        id?: T;
      };
  'latar-belakang'?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}